name: .NET Core Publish
 
on:
  push:
    branches: [ main ]
 
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
 
    - name: Publish with dotnet
      run: dotnet publish -c Release -o out
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: publish-artifact
        path: out