name: Build and Release

# 触发条件：当代码推送到主分支（或者其他分支）时触发工作流
on:
  push:
    branches:
      - main  # 你也可以根据需要修改为其他分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 .NET SDK（如果是 ASP.NET Core 或其他 .NET 项目）
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # 你可以修改为合适的 .NET 版本

      # 恢复项目依赖
      - name: Restore dependencies
        run: dotnet restore

      # 构建项目
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # 发布项目（打包输出）
      - name: Publish project
        run: dotnet publish --configuration Release --no-build --output ./publish

  release:
    runs-on: ubuntu-latest
    needs: build  # 确保 release 任务在 build 任务成功后执行

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 使用 GitHub API 创建 Release
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub 自动提供的令牌

      # 上传发布的文件到 GitHub Release
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: ./publish/*  # 指定要上传的文件路径，按需修改
